# Generated by Django 4.2.13 on 2024-05-19 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedbook',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='it', to='main.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=40, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('education', 'Образование'), ('entertainment', 'Периодични издания'), ('comics', 'Комикси'), ('biography', 'Биографични'), ('history', 'История'), ('novel', 'Романи'), ('fantasy', 'Фентъзи'), ('thriller', 'Трилъри'), ('romance', 'Романтика'), ('scifi', 'Научна фантастика')], default='education', max_length=30, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.PositiveIntegerField(default=0, verbose_name='Инв. №'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='Заглавие'),
        ),
    ]
